"use"
import type { Metadata } from "next";
import "./globals.css";
import { Inter, Geist } from 'next/font/google';
import './globals.css';
import { cn } from "@/lib/utils";
import SmoothScroll from "@/components/smootscrolling/SmoothScrolling";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});


// Configure the Inter font
const inter = Inter({
  subsets: ['latin'],
  display: 'swap', 
  variable: '--font-inter', // Defines a CSS v  ariable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable, inter.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
